### ISSUE TITLE
Support for RDRAND and RDSEED instructions?

### ISSUE THREAD

**Issue by Amaroq-Clearwater** [douglascrockford/fash#2]
Intel published an open-source C/C++ random number generator library titled DRNG, which automatically checks for and then—if supported by your CPU—makes use of the RDRAND and RDSEED CPU instructions. The x86-64 instruction set uses the RDRAND instruction for producing a True Random Number via integrated hardware. The RDSEED instruction is currently exclusive to Intel CPUs, but is am evolution of RDRAND.

If the "fash" library supports this method of getting a seed for randomness, then call me impressed. If it does not, however, then how difficult would it be to add support for this?

**Comment by Amaroq-Clearwater** [comment]
(As an unrelated comment, I'm mildly surprised at apparent lack of a DEC64 plug)

**Comment by douglascrockford** [comment]
You have the seed function. You can use it with DRNG.

What is a DEC64 plug?
